###############################################################################
# Name of the Imperative based CLI to generate web help for.
# The NPM package for the CLI must be installed either locally in this repo,
# or globally.
###############################################################################
cliPackage: "@zowe/cli"

###############################################################################
# List of command groups to exclude from generated docs.
# For example, if you have the CICS plugin globally installed but don't want
# it included in the docs, add "cics" to this list.
###############################################################################
excludeGroups:
  -

###############################################################################
# Specifies whether user's home directory should be redacted from help
# content.
###############################################################################
sanitizeHomeDir: yes

###############################################################################
# Specifies whether to build web help using a globally installed
# @zowe/imperative package, instead of the version installed locally in this
# repo.
###############################################################################
useGlobalImperative: no
